# Generated by Django 4.0.2 on 2024-04-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'snotice',
            },
        ),
    ]
